version: FasionMatching-v1
description: FasionMatching
time_version: False # if set ture, add time information in version
save_version_files: False # if set true, save each version files in runs
save_version_file_patterns:
  - "*.py"
  - "*.yaml"
pass_dirs:
  - '.'
  - '_'
  - 'runs'
  - 'results'

# filepath
train_dirs: ./efficient_fashion_matching/train_test_256/train
test_dirs: ./efficient_fashion_matching/train_test_256/test

cuda: True
# train
random_seed: 42
epochs: 300
batch_size: 128
num_workers: 16
lr: 1e-4
device_ids:
  - 4
  - 5
valid_every_epochs: 5
early_stop_epochs: -1
start_save_model_epochs: 300
save_model_interval_epochs: 1

# valid & test
match_factor: 3

# loss
arcface: True
m: 0.2
s: 32

# test
load_epoch: False # it will test your model if set a value, e.g. best, 10, 100