version: FasionMatching-v1
description: FasionMatching
time_version: False # if set ture, add time information in version
save_version_files: False # if set true, save each version files in runs
save_version_file_patterns:
  - "*.py"
  - "*.yaml"
pass_dirs:
  - '.'
  - '_'
  - 'runs'
  - 'results'

# filepath
train_dirs: ./efficient_fashion_matching/deepfashion_train_test_256/train_test_256/train
test_dirs: ./efficient_fashion_matching/deepfashion_train_test_256/train_test_256/test

# train
random_seed: 42
epochs: 100
batch_size: 128
num_workers: 0
lr: 1e-4
device_ids:
  - 0
valid_every_epochs: 1
early_stop_epochs: -1
start_save_model_epochs: 90
save_model_interval_epochs: 1

# loss
arcface: True
m: 0.1
s: 32

# test
load_epoch: False # it will test your model if set a value, e.g. best, 10, 100